export type SecurityType =
    | 'A BLANK value is possible'
    | 'Barbados Depository Receipts'
    | 'Bond'
    | 'Basket Warrant'
    | 'Convertible Debenture'
    | 'Share Depository Certificate'
    | 'Chess Depository Interest'
    | 'CEDEAR'
    | 'Convertible Notes'
    | 'Conversion'
    | 'Commodity'
    | 'Certificate'
    | 'Convertible Unsecured Loan Stock'
    | 'Currency'
    | 'Contingent Value Rights'
    | 'Covered Warrant'
    | 'Debenture'
    | 'Derivatives'
    | 'Depository Receipts'
    | 'Distribution Rights'
    | 'Deferred Settlement Trading'
    | 'Equity Shares'
    | 'Exchange Traded Commodities'
    | 'Exchange Traded Fund'
    | 'Exchange Traded Notes'
    | 'Fund'
    | 'Global Depository Notes'
    | 'Irredeemable Convertible Loan Stock'
    | 'Index'
    | 'Interval Fund'
    | 'Inflation'
    | 'Interbank Offered Rate'
    | 'Letter of Allotment'
    | 'Unit Trust'
    | 'Non Convertible Debenture'
    | 'Non-Redeemable Convertible Cumulative Preference S'
    | 'Notes'
    | 'Partly Convertible Debenture'
    | 'Perpetual Exchangeable Repurchaseable Listed Share'
    | 'Preferred Security'
    | 'Poison Pill Rights'
    | 'Preference Share'
    | 'Parallel Line'
    | 'Redeemable Convertible Secured Loan Stocks'
    | 'Redeemable Convertible Secured Notes'
    | 'Receipt'
    | 'Redemption Rights'
    | 'Redeemable Shares'
    | 'Redeemable Optional Convertible Preference Shares'
    | 'rights'
    | 'Redeemable Unconvertible Notes'
    | 'Structured Product'
    | 'Subscription Receipts'
    | 'Second Trading Line'
    | 'Stapled Security'
    | 'Swap Rate'
    | 'Tradeable Rights'
    | 'Tendered Shares Security'
    | 'Unit Investment Trust'
    | 'Units'
    | 'Warrants'
    | 'When Distributed'
    | 'When Issued';
